### ISSUE TITLE
Can't open webpage.

### ISSUE THREAD

**Issue by suraj022** [jandrassy/arduino-firmware-wifilink#9]
I'm trying to flash the firmware on a generic nodemcu board using the "UNOWIFIDEVED" parameters
firmware flashes successfully and SSID appears (and connects). I've also uploaded sketch data folder using "esp8266 sketch data uploader" tool.
But the webpage doesn't seem to open by pointing my browser to 192.168.240.1
Am I missing anything?

**Comment by JAndrassy** [comment]
please try 192.168.4.1

**Comment by suraj022** [comment]
@jandrassy tried it without any success. Anyways, default IP in the code is set to 192.168.240.1

Also I noticed just now that my android phone fails to obtain IP address from the AP. which means DHCP might not be running?

**Comment by JAndrassy** [comment]
try to flash the firmware with Tools menu option "Erase flash: Sketch + WiFi Settings"

**Comment by suraj022** [comment]
Did that aswell. no change. webpage still wont load.

**Comment by JAndrassy** [comment]
I found the error. Fix is committed. It was an old bug by arduino.org coders. I should have noticed it much earlier.  Maybe on older esp8266 core versions it did less damage.

**Comment by suraj022** [comment]
Thanks. but it still wont load. I can't even ping to the module.
![Capture](https://user-images.githubusercontent.com/40080503/67855007-9b5f5500-fb37-11e9-934d-e25aedcc28a7.JPG)

**Comment by JAndrassy** [comment]
try to flash some ESP8266 example for example  BasicHttpClient to connect to your AP and let the esp8266 store the ssid and password. Then upload the WiFiLink firmware and it should connect to AP and be accessible in that network

**Comment by JAndrassy** [comment]
I hope you didn't select Arduino/Uno WiFi to upload the firmware. it would not work on NodeMcu

**Comment by suraj022** [comment]
> I hope you didn't select Arduino/Uno WiFi to upload the firmware. it would not work on NodeMcu

yes ofcourse. the  wouldn't compile on "Arduino/Uno WiFi". anyways. Connecting nodemcu to a AP is not an option here As I plan to use it only in AP mode.

Arduino (Uno WiFi) is esp8266 'board'. it would compile. but with 40 MHz crystal setting

join some AP to test if the problem is only the SoftAP mode. it will help me troubleshoot

**Comment by suraj022** [comment]
> try to flash some ESP8266 example for example BasicHttpClient to connect to your AP and let the esp8266 store the ssid and password. Then upload the WiFiLink firmware and it should connect to AP and be accessible in that network

Just did that. and it does work when connect to  an access point( i.e. in STA mode)

**Comment by JAndrassy** [comment]
and SoftAP still doesn't work?

**Comment by suraj022** [comment]
> and SoftAP still doesn't work?

No.

**Comment by JAndrassy** [comment]
could you try to switch modes in WebPanel? to STA and then back to AP+STA

**Comment by suraj022** [comment]
> could you try to switch modes in WebPanel? to STA and then back to AP+STA

Yes. works in this way in AP+STA mode. but not when I freshly upload the code.

**Comment by JAndrassy** [comment]
and after fresh upload now with flash erase is it available as STA?

**Comment by suraj022** [comment]
> and after fresh upload now with flash erase is it available as STA?

Yes works with STA mode.

**Comment by JAndrassy** [comment]
AP is not started if esp8266 has stored STA mode
https://github.com/jandrassy/arduino-firmware-wifilink/blob/c634eca7f34a117f0f3a8167f482636c74c616d1/ArduinoFirmwareEsp/ArduinoFirmwareEsp.ino#L110

**Comment by suraj022** [comment]
~~I've found a potential fix. by commenting out the `initHostname();` function in `void setup()` the code works normally in both STA mode and AP mode.~~

Doesn't work this way aswell.
